### ISSUE TITLE
Port 80 already in use

### ISSUE THREAD

**Issue by cocolitto** [mpous/balena-nodered-mqtt#1]
Hi,

I'm using balena with an private TTS stack and gateway (basicstation) on an Raspberry 3. I would like to stay localy in my net . 
The TTS (stack) container is already using port 80. 
Now i would like to integrate your NodeRed container to handle the data receiving from the TTS. 

Could you tell me an easy way to change the port of the Nodered to something different than 80?

here the error log from the node-red container:

node-red  22 Nov 18:02:05 - [warn] Flows file name not set. Generating name using hostname.
node-red  22 Nov 18:02:05 - [info] Flows file     : /data/node-red/user/flows_22a2dbd.json
node-red  22 Nov 18:02:05 - [info] Creating new flow file
node-red  22 Nov 18:02:05 - [error] Unable to listen on http://127.0.0.1:80/
node-red  22 Nov 18:02:05 - [error] Error: port in use

best regards 
Corsin Obrist

**Comment by alexcorvis84** [comment]
Looking at the [docker-compose.yml](https://github.com/mpous/ming/blob/master/docker-compose.yml), I think you could change the Node-RED `HOST_PORT` 80 port (see ports):

```
node-red:
    image: bh.cr/balenablocks/balena-node-red
    container_name: node-red
    privileged: true
    restart: unless-stopped
    volumes:
        - 'node-red-data:/data'
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
    ports:
        - 80:80
    environment:
        PORT: 80
        USERNAME: "balena"
        PASSWORD: "balena"
        ENCRIPTION_KEY: "balena"        
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
        - "/dev/i2c-1:/dev/i2c-1"
```
